- "Self Hosted":
    - Uptime Kuma:
        abbr: UK
        icon: /icons/uptimekuma.png
        #href: http://uptime.lan
        href: http://svc1.lan:3001/
        description: Monitoring
        widget:
            type: uptimekuma
            url: http://svc1.lan:3001
            # slug: What dashboard to show
            slug: dashboard
            #slug: hosts
    - Photoprism:
        abbr: PP
        icon: /icons/photoprism.example.com.ico.png
        #href: https://photoprism.example.com
        href: http://photoprism.lan
        description: Photos
        widget:
            type: photoprism
            url: http://photoprism.lan
            username: XXX
            password: XXX
            fields: [ "albums", "photos", "videos"]
    - QBittorrent:
        abbr: QT
        icon: /icons/qbittorrent.svg
        #href: http://svc1.lan:8084/
        href: http://torrent.lan
        description: torrent client
        widget:
            type: qbittorrent
            #url: http://torrent.lan
            url: http://svc2.lan:8084
            username: XXX
            password: XXX
            fields: [ "download", "seed", "upload" ]
    - Miniflux:
        abbr: MF
        icon: /icons/miniflux.ico.png
        #href: http://svc1.lan:8085/unread
        href: http://miniflux.lan/unread
        description: RSS
        widget:
         type: miniflux
         #url: http://svc1.lan:8085/
         url: http://172.16.0.34:8085/
         key: "XXX"
    - Paperless:
        abbr: PL
        icon: paperless.png
        href: http://svc1.lan:8000
        description: paperless
    - Home Assistant:
        abbr: HA
        icon: home-assistant.png
        href: https://ha.example.com
        description: Home Assistant
    - Gitea:
        abbr: GT
        icon: /icons/git.example.com.ico.png
        href: https://git.example.com/
        description: git ui
    - Traefik:
        abbr: TR
        icon: /icons/traefik.svg
        href: http://svc1.lan:8089
        description: traefik load balancer
    - Jellyfin:
        abbr: JF
        icon: /icons/jellyfin.svg
        #href: http://video.lan:8096/
        href: http://jellyfin.lan
        description: media
    - Plex:
        #abbr: JF
        icon: /icons/plex.png
        #href: http://video.lan:32400
        href: http://plex.lan
        description: media
    - Immich:
        abbr: IM
        icon: /icons/immich.png
        href: http://svc2.lan:2283/
        description: Immich

- Syncthing:
    - Svc1:
        href: http://svc1.lan:8384/
        icon: syncthing.png
    - Svc2:
        href: http://svc2.lan:8384/
        icon: syncthing.png

# - More:
#     - Calendar:
#         href: https://app.fastmail.com/calendar/month
#         icon: fastmail.png
#         widget:
#             type: calendar
