---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/service-widgets

- resources:
    cpu: true
    memory: true
    disk: /

- search:
    provider: duckduckgo
    target: _blank

- stocks:
    provider: finnhub
    color: true # optional, defaults to true
    cache: 1 # optional, default caches results for 1 minute
    watchlist:
     - NVDA
     # # Composite indexes
     # # S&P 500
     # - GSPC
     # # Dow jones industrial average
     # - DJI
     # # Nasdaq composite
     # - IXIC
